package com.airohit.agriculture.module.system.api.errorcode;

import com.airohit.agriculture.framework.common.pojo.CommonResult;
import com.airohit.agriculture.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import com.airohit.agriculture.module.system.api.errorcode.dto.ErrorCodeRespDTO;

import java.time.LocalDateTime;
import java.util.List;

public interface ErrorCodeApi {

    CommonResult<Boolean> autoGenerateErrorCodes(List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs);

    CommonResult<List<ErrorCodeRespDTO>> getErrorCodeList(String applicationName, LocalDateTime minUpdateTime);

}
