export const CODES = {
    // 沙尘暴
    Sandstorm: 1,
    // 雷暴
    Thunderstorm: 2,
    // 冰雹
    Hail: 3,
    // 吹雪
    BlowingSnow: 4,
    // 阵雪
    Snowstorm: 5,
    // 中雪
    Snow: 6,
    // 小雪
    LittleSnow: 7,
    // 雨夹雪
    RainSnow: 8,
    // 阵雨
    Shower: 9,
    // 零星阵雨
    SporadicShowers: 10,
    // 局地阵雨
    LocalShowers: 11,
    // 阵雨
    LittleShower: 12,
    // 冻雨
    FrozenRain: 13,
    // 中雨
    Rain: 14,
    // 小雨
    Drizzle: 15,
    // 雾
    Mist: 16,
    // 轻雾
    Little_Mist: 17,
    // 烟雾
    Smoke: 18,
    // 霾
    Haze: 19,
    // 阴
    Yin: 20,
    // 多云间晴
    CloudySunny: 21,
    // 多云
    Cloudy: 22,
    // 晴
    Sunny: 23,
    // 风
    Wind: 24,
    // 潮湿
    Wet: 25,
    // 干燥
    Dry: 26,
    // 冰冻
    Frozen: 27,
    // 霜冻
    Frost: 28,
    // 炎热
    Hot: 29,
    // 寒冷
    Cold: 30,
    // 暖和
    Warm: 31,
    // 清凉
    CoolRefreshing: 32,
    // 火山灰
    VolcanicAsh: 33
};

export const MATCH = {
    [CODES.Sandstorm]: 'https://worldweather.wmo.int/images/1.png',
    [CODES.Thunderstorm]: 'https://worldweather.wmo.int/images/2.png',
    [CODES.Hail]: 'https://worldweather.wmo.int/images/3.png',
    [CODES.BlowingSnow]: 'https://worldweather.wmo.int/images/4.png',
    [CODES.Snowstorm]: 'https://worldweather.wmo.int/images/5.png',
    [CODES.Snow]: 'https://worldweather.wmo.int/images/6.png',
    [CODES.LittleSnow]: 'https://worldweather.wmo.int/images/7.png',
    [CODES.RainSnow]: 'https://worldweather.wmo.int/images/8.png',
    [CODES.Shower]: 'https://worldweather.wmo.int/images/9.png',
    [CODES.SporadicShowers]: 'https://worldweather.wmo.int/images/10.png',
    [CODES.LocalShowers]: 'https://worldweather.wmo.int/images/11.png',
    [CODES.LittleShower]: 'https://worldweather.wmo.int/images/12.png',
    [CODES.FrozenRain]: 'https://worldweather.wmo.int/images/13.png',
    [CODES.Rain]: 'https://worldweather.wmo.int/images/14.png',
    [CODES.Drizzle]: 'https://worldweather.wmo.int/images/15.png',
    [CODES.Mist]: 'https://worldweather.wmo.int/images/16.png',
    [CODES.Little_Mist]: 'https://worldweather.wmo.int/images/17.png',
    [CODES.Smoke]: 'https://worldweather.wmo.int/images/18.png',
    [CODES.Haze]: 'https://worldweather.wmo.int/images/19.png',
    [CODES.Yin]: 'https://worldweather.wmo.int/images/20.png',
    [CODES.CloudySunny]: 'https://worldweather.wmo.int/images/21a.png',
    [CODES.Cloudy]: 'https://worldweather.wmo.int/images/22a.png',
    [CODES.Sunny]: 'https://worldweather.wmo.int/images/24a.png',
    [CODES.Wind]: 'https://worldweather.wmo.int/images/26.png',
    [CODES.Wet]: 'https://worldweather.wmo.int/images/27.png',
    [CODES.Dry]: 'https://worldweather.wmo.int/images/28.png',
    [CODES.Frozen]: 'https://worldweather.wmo.int/images/29.png',
    [CODES.Frost]: 'https://worldweather.wmo.int/images/30.png',
    [CODES.Hot]: 'https://worldweather.wmo.int/images/31.png',
    [CODES.Cold]: 'https://worldweather.wmo.int/images/32.png',
    [CODES.Warm]: 'https://worldweather.wmo.int/images/33.png',
    [CODES.CoolRefreshing]: 'https://worldweather.wmo.int/images/34.png',
    [CODES.VolcanicAsh]: 'https://worldweather.wmo.int/images/35.png',
};
