import {WEATHER_CONFIG} from '@/utils/weatherConfig.js'

const {
    WEATHER_PHENOMENON,
    TEMPRATURE,
    APPARENT_TEMPRATURE,
    RELATIVE_HUMIDITY,
    WIND_LEVEL,
    WIND_SPEED,
    WIND_DIRECTION,
    WIND_ANGLE,
    RAINFALL_1_HOUR,
    CLOUDINESS,
    HORIZONTAL_VISIBILITY,
    PRESSURE,
    LEAKAGE_TEMPRATURE,
    UV_INDEX
} = WEATHER_CONFIG;

export const WEATHER_LIST = [
    WEATHER_PHENOMENON,
    TEMPRATURE,
    APPARENT_TEMPRATURE,
    RELATIVE_HUMIDITY,
    WIND_LEVEL,
    WIND_SPEED,
    WIND_DIRECTION,
    WIND_ANGLE,
    RAINFALL_1_HOUR,
    CLOUDINESS,
    HORIZONTAL_VISIBILITY,
    PRESSURE,
    LEAKAGE_TEMPRATURE,
    UV_INDEX
] 